
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootProvider from "@/providers/root-provider";
import Navbar from "@/components/layout/navbar";
import MobileBottomNav from "@/components/layout/bottom-nav";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<RootProvider>
					<Navbar />
					<MobileBottomNav />
					<div className="pt-[72px]">{children}</div>
				</RootProvider>
			</body>
		</html>
	);
}
